version: "3"
services:
  app:
    build: docker/app/
    volumes:
      - ./src:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7.41
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/mysql_data:/var/lib/mysql
    env_file:
      - docker/db/db-variables.env
